pluginManagement {
    repositories {
        maven {
            name = 'Aliyun Gradle Plugin'
            url = 'https://maven.aliyun.com/repository/gradle-plugin'
        }
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge (BMCLAPI)'
            url = 'https://bmclapi2.bangbang93.com/maven/'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
